###############################################################################
# General Configuration
###############################################################################
version: 1.0.{build}

###############################################################################
# Environment Configuration
###############################################################################
image: Visual Studio 2017

configuration: 
 - Release
 - Debug
platform: 
  - x64
  - x86

###############################################################################
# Build Configuration
###############################################################################
build:
  project: MiniEngine\ModelViewer\ModelViewer_VS15.sln
  verbosity: normal